version: '3'
services:
  devbox:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
  devmysql:
    build:
      context: ./
      dockerfile: MySQLDev.Dockerfile
    ports:
      - "3306:3306"
 